import bcrypt from "bcryptjs";
import { v4 as uuidv4 } from "uuid";
import { query } from "./db.js";

export async function seed() {
  try {
    const now = new Date().toISOString();

    // Clear old products to ensure fresh real-data seed
    await query("DELETE FROM stock_log").catch(()=>{});
    await query("DELETE FROM orders").catch(()=>{});
    await query("DELETE FROM reviews").catch(()=>{});
    await query("DELETE FROM products").catch(()=>{});

    /* ─── Categories ─── */
    const categories = [
      { name: "Laptops", slug: "laptops", icon: "laptop", description: "High-performance laptops for work, gaming, and creation", featured: true, order: 1 },
      { name: "Smartphones", slug: "phones", icon: "smartphone", description: "Latest smartphones with cutting-edge technology", featured: true, order: 2 },
      { name: "Gaming PCs", slug: "gaming-pcs", icon: "gamepad-2", description: "Ultimate gaming rigs for every budget", featured: true, order: 3 },
      { name: "Tablets", slug: "tablets", icon: "tablet", description: "Versatile tablets for productivity and entertainment", featured: true, order: 4 },
      { name: "Watches", slug: "watches", icon: "watch", description: "Smartwatches and wearable tech", featured: true, order: 5 },
      { name: "Headphones & Audio", slug: "headphones", icon: "headphones", description: "Premium audio gear from top brands", featured: true, order: 6 },
      { name: "Accessories", slug: "accessories", icon: "keyboard", description: "Essential accessories to complete your setup", featured: true, order: 7 },
      { name: "Game Top-Ups", slug: "game-topup", icon: "dices", description: "Digital game credits and in-game currency", featured: false, order: 8 },
      { name: "Gift Cards", slug: "gift-cards", icon: "gift", description: "Digital gift cards for all occasions", featured: false, order: 9 },
    ];
    for (const c of categories) {
      const exists = await query("SELECT id FROM categories WHERE slug = $1", [c.slug]);
      if (exists.rows.length > 0) continue;
      const id = uuidv4();
      await query('INSERT INTO categories (id, name, slug, description, icon, featured, "order") VALUES ($1,$2,$3,$4,$5,$6,$7)', [id, c.name, c.slug, c.description, c.icon, c.featured, c.order]);
    }

    /* ─── Products ─── */
    const products = [
      /* ── LAPTOPS ── */
      { name: 'MacBook Air 13" M5 (2026)', category: "laptops", price: 1099, originalPrice: 1199, stock: 20, badge: "New", rating: 4.9, reviews: 342, description: "Apple M5 chip with 12-core CPU and 18-core GPU, 16GB unified memory, 256GB SSD, 13.6-inch Liquid Retina display. Up to 18 hours of battery life in a fanless design.", features: ["Apple M5 chip (12-core CPU, 18-core GPU)", "16GB unified memory", "256GB SSD storage", "13.6-inch Liquid Retina display", "18-hour battery life", "MagSafe charging", "Two Thunderbolt 4 ports"], images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400"] },
      { name: 'MacBook Pro 14" M5 Pro (2025)', category: "laptops", price: 1999, stock: 12, badge: "Best Seller", rating: 4.9, reviews: 567, description: "Apple M5 Pro chip, 24GB unified memory, 512GB SSD, 14.2-inch Liquid Retina XDR display. Pro-level performance for demanding workflows.", features: ["Apple M5 Pro (14-core CPU, 20-core GPU)", "24GB unified memory", "512GB SSD", "14.2-inch Liquid Retina XDR", "Up to 17 hours battery", "HDMI 2.1, SDXC, MagSafe", "Three Thunderbolt 5 ports"], images: ["https://images.unsplash.com/photo-1517445312882-bc9910abeb7b?w=400"] },
      { name: 'Dell XPS 14 (2026)', category: "laptops", price: 1699, originalPrice: 1899, stock: 15, rating: 4.7, reviews: 234, description: "14.5-inch 3.2K OLED, Intel Core Ultra 7 265H, 16GB RAM, 512GB SSD. Premium ultrabook with infinity edge display.", features: ["14.5-inch 3.2K OLED touch display", "Intel Core Ultra 7 265H", "16GB LPDDR5x RAM", "512GB PCIe Gen 5 SSD", "Intel Arc Graphics", "Wi-Fi 7 + Bluetooth 5.4", "CNC machined aluminum chassis"], images: ["https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400"] },
      { name: 'HP Spectre x360 14', category: "laptops", price: 1449, stock: 10, badge: "Featured", rating: 4.6, reviews: 189, description: "14-inch 2.8K OLED 2-in-1, Intel Core Ultra 7, 16GB RAM, 1TB SSD. Convertible with incredible battery life.", features: ["14-inch 2.8K OLED touch display", "Intel Core Ultra 7 256V", "16GB LPDDR5x RAM", "1TB PCIe Gen 5 SSD", "360° hinge design", "HP Spectre pen included", "17-hour battery life"], images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400"] },
      { name: 'Lenovo ThinkPad X1 Carbon Gen 13', category: "laptops", price: 1999, stock: 8, rating: 4.7, reviews: 156, description: "14-inch 2.8K OLED, Intel Core Ultra 7, 32GB RAM, 1TB SSD. Ultralight at 2.4 lbs with MIL-STD-810H durability and TrackPoint.", features: ["14-inch 2.8K OLED display", "Intel Core Ultra 7 165H", "32GB LPDDR5x RAM", "1TB PCIe Gen 5 SSD", "2.4 lbs ultralight", "MIL-STD-810H certified", "Thunderbolt 4 + HDMI 2.1"], images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400"] },
      { name: 'ASUS ROG Zephyrus G16', category: "laptops", price: 2199, stock: 7, badge: "Gaming", rating: 4.8, reviews: 423, description: "16-inch 2.5K 240Hz OLED, Intel Core Ultra 9, RTX 4070, 32GB DDR5, 1TB SSD. Ultra-slim gaming powerhouse.", features: ["16-inch 2.5K 240Hz OLED display", "Intel Core Ultra 9 285HX", "NVIDIA RTX 4070 8GB", "32GB DDR5 RAM", "1TB PCIe Gen 5 SSD", "0.7-inch thin profile", "RGB keyboard with per-key lighting"], images: ["https://images.unsplash.com/photo-1603302576837-37561b5b0e7d?w=400"] },
      { name: 'ASUS Zenbook 14 OLED', category: "laptops", price: 999, originalPrice: 1199, stock: 25, rating: 4.5, reviews: 678, description: "14-inch 2.8K OLED 120Hz, AMD Ryzen 7, 16GB RAM, 512GB SSD. Best value premium ultrabook with stunning OLED display.", features: ["14-inch 2.8K OLED 120Hz", "AMD Ryzen 7 8840HS", "16GB LPDDR5 RAM", "512GB PCIe Gen 4 SSD", "0.6-inch thin, 2.8 lbs", "75Wh battery", "Harmon Kardon audio"], images: ["https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400"] },
      { name: 'Razer Blade 16 (2025)', category: "laptops", price: 2999, stock: 5, badge: "Premium", rating: 4.9, reviews: 198, description: "16-inch 4K 120Hz Mini LED, Intel Core i9, RTX 4090, 32GB DDR5, 2TB SSD. The ultimate gaming laptop with CNC aluminum unibody.", features: ["16-inch 4K 120Hz Mini LED display", "Intel Core i9-14900HX", "NVIDIA RTX 4090 16GB", "32GB DDR5-5600 RAM", "2TB PCIe Gen 5 SSD", "CNC aluminum unibody", "THX spatial audio"], images: ["https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=400"] },
      { name: 'MSI Raider 18 HX AI', category: "laptops", price: 3499, stock: 3, badge: "Ultimate", rating: 4.8, reviews: 89, description: "18-inch 4K 120Hz Mini LED, Intel Core i9, RTX 4090, 64GB DDR5, 2TB SSD. Flagship gaming laptop with AI-powered optimization.", features: ["18-inch 4K 120Hz Mini LED", "Intel Core i9-14900HX", "NVIDIA RTX 4090 16GB", "64GB DDR5-5600 RAM", "2TB PCIe Gen 5 SSD (RAID 0)", "Cherry MX mechanical keyboard", "AI engine for performance tuning"], images: ["https://images.unsplash.com/photo-1603302576837-37561b40f3a0?w=400"] },
      { name: 'Framework Laptop 13', category: "laptops", price: 1049, stock: 30, rating: 4.6, reviews: 267, description: "13.5-inch 2.8K display, AMD Ryzen 7 7840U, 16GB RAM, 1TB SSD. Fully modular, repairable, and upgradeable laptop.", features: ["13.5-inch 2.8K 3:2 display", "AMD Ryzen 7 7840U", "16GB DDR5 RAM (user upgradeable)", "1TB NVMe SSD (user upgradeable)", "Fully modular design", "Expansion Card ports (USB-C, HDMI, etc.)", "100% recycled aluminum chassis"], images: ["https://images.unsplash.com/photo-1504730653489-53c16bba9a8f?w=400"] },

      /* ── PHONES ── */
      { name: 'iPhone 11 (128GB)', category: "phones", price: 249, originalPrice: 399, stock: 45, rating: 4.4, reviews: 12345, description: "6.1-inch Liquid Retina display, A13 Bionic chip, Dual 12MP camera system, 4K video recording. Certified refurbished.", features: ["6.1-inch Liquid Retina LCD", "A13 Bionic chip", "Dual 12MP (wide + ultra-wide)", "4K video at 60fps", "Face ID", "IP68 water resistance", "Wireless charging"], images: ["https://images.unsplash.com/photo-1592434134756-a70b96f27062?w=400"] },
      { name: 'iPhone 12 (128GB)', category: "phones", price: 349, originalPrice: 499, stock: 38, rating: 4.5, reviews: 10234, description: "6.1-inch Super Retina XDR OLED, A14 Bionic, Ceramic Shield, 5G support. Certified refurbished.", features: ["6.1-inch Super Retina XDR OLED", "A14 Bionic chip", "Dual 12MP camera system", "Ceramic Shield front cover", "5G connectivity", "MagSafe support", "IP68 water resistance"], images: ["https://images.unsplash.com/photo-1605773527852-c546a8584ea3?w=400"] },
      { name: 'iPhone 13 (128GB)', category: "phones", price: 449, originalPrice: 599, stock: 32, rating: 4.6, reviews: 8765, description: "6.1-inch Super Retina XDR OLED, A15 Bionic, Cinematic mode, up to 19 hours battery.", features: ["6.1-inch Super Retina XDR OLED", "A15 Bionic chip", "Dual 12MP camera with sensor-shift OIS", "Cinematic mode 1080p@30fps", "Up to 19 hours video playback", "Face ID", "IP68 water resistance"], images: ["https://images.unsplash.com/photo-1530268729831-4b0b9e598218?w=400"] },
      { name: 'iPhone 14 (128GB)', category: "phones", price: 599, originalPrice: 699, stock: 28, rating: 4.6, reviews: 6543, description: "6.1-inch Super Retina XDR OLED, A15 Bionic, improved cameras, crash detection, satellite SOS.", features: ["6.1-inch Super Retina XDR OLED", "A15 Bionic chip (5-core GPU)", "Dual 12MP camera with Action mode", "Crash Detection", "Emergency SOS via satellite", "Up to 20 hours video playback", "Bluetooth 5.3"], images: ["https://images.unsplash.com/photo-1574755393849-623942496936?w=400"] },
      { name: 'iPhone 15 (128GB)', category: "phones", price: 729, stock: 22, badge: "Popular", rating: 4.7, reviews: 5432, description: "6.1-inch Super Retina XDR OLED, A16 Bionic, 48MP main camera, Dynamic Island, USB-C.", features: ["6.1-inch Super Retina XDR OLED", "A16 Bionic chip", "48MP main + 12MP ultra-wide", "Dynamic Island", "USB-C with USB 2.0", "Up to 20 hours video playback", "Second-gen UWB chip"], images: ["https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=400"] },
      { name: 'iPhone 15 Plus (128GB)', category: "phones", price: 829, stock: 18, rating: 4.7, reviews: 3210, description: "6.7-inch Super Retina XDR OLED, A16 Bionic, 48MP camera, Dynamic Island, USB-C. Bigger screen, bigger battery.", features: ["6.7-inch Super Retina XDR OLED", "A16 Bionic chip", "48MP main + 12MP ultra-wide", "Dynamic Island", "USB-C with USB 2.0", "Up to 26 hours video playback", "Aluminum with color-infused glass"], images: ["https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400"] },
      { name: 'iPhone 16 (128GB)', category: "phones", price: 799, stock: 25, badge: "New", rating: 4.8, reviews: 4123, description: "6.1-inch Super Retina XDR OLED, A18 chip, Camera Control button, Apple Intelligence ready.", features: ["6.1-inch Super Retina XDR OLED", "A18 chip (3nm)", "48MP fusion camera system", "Camera Control button", "Apple Intelligence support", "Up to 22 hours video playback", "Action button"], images: ["https://images.unsplash.com/photo-1731541912250-38307e05148f?w=400"] },
      { name: 'iPhone 16 Plus (128GB)', category: "phones", price: 899, stock: 20, rating: 4.8, reviews: 2876, description: "6.7-inch Super Retina XDR OLED, A18 chip, Camera Control, Apple Intelligence. Large screen, pro-level features.", features: ["6.7-inch Super Retina XDR OLED", "A18 chip (3nm)", "48MP fusion camera system", "Camera Control button", "Apple Intelligence support", "Up to 27 hours video playback", "Action button"], images: ["https://images.unsplash.com/photo-1731541912250-38307e05148f?w=400"] },
      { name: 'iPhone 16 Pro (256GB)', category: "phones", price: 1199, originalPrice: 1299, stock: 14, badge: "Best Seller", rating: 4.9, reviews: 5678, description: "6.3-inch Super Retina XDR OLED, A18 Pro chip, 48MP fusion + 48MP ultra-wide + 5x telephoto, titanium design.", features: ["6.3-inch Super Retina XDR OLED", "A18 Pro chip (3nm)", "48MP fusion + 48MP ultra-wide + 12MP 5x telephoto", "Titanium frame", "Camera Control button", "Up to 27 hours video playback", "Wi-Fi 7 + Thread radio"], images: ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400"] },
      { name: 'iPhone 16 Pro Max (256GB)', category: "phones", price: 1299, stock: 10, badge: "Premium", rating: 4.9, reviews: 7890, description: "6.9-inch Super Retina XDR OLED, A18 Pro chip, 48MP fusion + 48MP ultra-wide + 5x telephoto, titanium, largest battery ever.", features: ["6.9-inch Super Retina XDR OLED", "A18 Pro chip (3nm)", "48MP fusion + 48MP ultra-wide + 12MP 5x telephoto", "Titanium frame", "Up to 33 hours video playback", "Camera Control button", "Wi-Fi 7 + Thread radio"], images: ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400"] },
      { name: 'iPhone 17e (128GB)', category: "phones", price: 599, stock: 30, rating: 4.6, reviews: 1234, description: "6.1-inch Super Retina XDR OLED, A19 chip, single 48MP camera, Apple Intelligence. The most affordable new iPhone.", features: ["6.1-inch Super Retina XDR OLED", "A19 chip (3nm)", "48MP single camera system", "Apple Intelligence support", "USB-C with USB 3.0", "Up to 21 hours video playback", "Action button"], images: ["https://images.unsplash.com/photo-1530268729831-4b0b9e598218?w=400"] },
      { name: 'iPhone 17 (128GB)', category: "phones", price: 799, stock: 22, badge: "New", rating: 4.7, reviews: 2345, description: "6.1-inch Super Retina XDR OLED, A19 chip, dual 48MP camera, Apple Intelligence, Always-On display.", features: ["6.1-inch Super Retina XDR OLED", "A19 chip (3nm)", "48MP fusion + 48MP ultra-wide", "Apple Intelligence", "Always-On display", "Up to 23 hours video playback", "Action button"], images: ["https://images.unsplash.com/photo-1731541912250-38307e05148f?w=400"] },
      { name: 'iPhone 17 Pro (256GB)', category: "phones", price: 1199, stock: 12, badge: "Featured", rating: 4.8, reviews: 1876, description: "6.3-inch Super Retina XDR OLED, A19 Pro chip, 48MP fusion + 48MP ultra-wide + 6x telephoto, titanium.", features: ["6.3-inch Super Retina XDR OLED", "A19 Pro chip (3nm)", "48MP fusion + 48MP ultra-wide + 12MP 6x telephoto", "Titanium frame", "Apple Intelligence Pro", "Up to 28 hours video playback", "Wi-Fi 8 ready"], images: ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400"] },
      { name: 'iPhone 17 Pro Max (256GB)', category: "phones", price: 1299, stock: 8, badge: "Ultimate", rating: 4.9, reviews: 3456, description: "6.9-inch Super Retina XDR OLED, A19 Pro chip, 48MP fusion + 48MP ultra-wide + 6x telephoto, titanium, pro camera system.", features: ["6.9-inch Super Retina XDR OLED", "A19 Pro chip (3nm)", "48MP fusion + 48MP ultra-wide + 12MP 6x telephoto", "Titanium frame", "Apple Intelligence Pro", "Up to 34 hours video playback", "Wi-Fi 8 ready"], images: ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400"] },
      { name: 'Samsung Galaxy S25', category: "phones", price: 799, stock: 28, rating: 4.6, reviews: 2341, description: "6.2-inch Dynamic AMOLED 2X 120Hz, Snapdragon 8 Gen 4, 50MP+12MP+10MP camera, Galaxy AI.", features: ["6.2-inch Dynamic AMOLED 2X 120Hz", "Snapdragon 8 Gen 4 (3nm)", "50MP + 12MP + 10MP triple camera", "Galaxy AI suite", "4000mAh battery", "IP68 water resistance", "One UI 7, 7 years of updates"], images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400"] },
      { name: 'Samsung Galaxy S25+', category: "phones", price: 999, stock: 20, rating: 4.7, reviews: 1876, description: "6.7-inch Dynamic AMOLED 2X 120Hz, Snapdragon 8 Gen 4, 50MP+12MP+10MP camera, larger battery.", features: ["6.7-inch Dynamic AMOLED 2X 120Hz", "Snapdragon 8 Gen 4 (3nm)", "50MP + 12MP + 10MP triple camera", "Galaxy AI suite", "4900mAh battery", "45W super fast charging", "UWB support"], images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400"] },
      { name: 'Samsung Galaxy S25 Ultra', category: "phones", price: 1299, stock: 15, badge: "Premium", rating: 4.9, reviews: 4567, description: "6.9-inch Dynamic AMOLED 2X 120Hz, Snapdragon 8 Gen 4, 200MP+50MP+12MP+10MP camera, S Pen, titanium.", features: ["6.9-inch Dynamic AMOLED 2X 120Hz", "Snapdragon 8 Gen 4 (3nm)", "200MP + 50MP + 12MP + 10MP quad camera", "S Pen included", "5000mAh battery", "Titanium frame", "Galaxy AI + 7 years of updates"], images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400"] },
      { name: 'Samsung Galaxy S24 FE', category: "phones", price: 649, stock: 35, rating: 4.5, reviews: 3120, description: "6.7-inch Dynamic AMOLED 2X 120Hz, Exynos 2400, 50MP+12MP+8MP camera, great value flagship.", features: ["6.7-inch Dynamic AMOLED 2X 120Hz", "Exynos 2400 (4nm)", "50MP + 12MP + 8MP triple camera", "Galaxy AI features", "4700mAh battery", "IP68 water resistance", "4 generations of OS updates"], images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400"] },

      /* ── GAMING PCS ── */
      { name: 'ROG G22CH Gaming Desktop', category: "gaming-pcs", price: 2999, stock: 5, badge: "Best Seller", rating: 4.9, reviews: 67, description: "Compact 10L chassis. Intel Core i9-14900K, NVIDIA RTX 4090, 64GB DDR5, 2TB SSD. Liquid-cooled for extreme performance.", features: ["Compact 10L chassis design", "Intel Core i9-14900K (24 cores)", "NVIDIA RTX 4090 24GB", "64GB DDR5-6000 RAM", "2TB NVMe SSD", "Custom 240mm AIO liquid cooling", "Wi-Fi 7 + 2.5G LAN"], images: ["https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=400"] },
      { name: 'Corsair Vengeance Gaming PC', category: "gaming-pcs", price: 2199, originalPrice: 2499, stock: 7, rating: 4.7, reviews: 43, description: "Mid-tower with AMD Ryzen 7 7800X3D, RTX 4070 Ti Super, 32GB DDR5, 1TB SSD. Perfect for 1440p gaming.", features: ["AMD Ryzen 7 7800X3D", "NVIDIA RTX 4070 Ti Super 16GB", "32GB DDR5-6000 RAM", "1TB NVMe SSD", "Corsair 5000D Airflow case", "Fully modular PSU", "Windows 11 Home"], images: ["https://images.unsplash.com/photo-1593640495253-23196b27a87f?w=400"] },
      { name: 'RTX 5090 Liquid Cooled Workstation', category: "gaming-pcs", price: 4999, stock: 2, badge: "Premium", rating: 5.0, reviews: 12, description: "Dual NVIDIA RTX 5090s, Threadripper PRO 7995WX, 128GB ECC DDR5, 4TB Gen5 SSD. Absolute peak performance.", features: ["Dual NVIDIA RTX 5090 32GB each", "AMD Threadripper PRO 7995WX (96 cores)", "128GB ECC DDR5 RAM", "4TB Gen5 NVMe SSD", "Custom water cooling loop", "2000W Platinum PSU", "Professional workstation case"], images: ["https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400"] },

      /* ── TABLETS ── */
      { name: 'iPad Pro 13" M5 (2025)', category: "tablets", price: 1299, stock: 14, badge: "New", rating: 4.8, reviews: 345, description: "Ultra-thin design with M5 chip, 13-inch Ultra Retina XDR tandem OLED, Apple Pencil Pro support, Wi-Fi 7.", features: ["13-inch Ultra Retina XDR tandem OLED", "Apple M5 chip (10-core CPU, 10-core GPU)", "16GB unified memory", "512GB SSD storage", "Thunderbolt 5 + USB-C", "Face ID", "Wi-Fi 7 + Bluetooth 5.4"], images: ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400"] },
      { name: 'iPad Air 11" M4 (2025)', category: "tablets", price: 599, stock: 22, rating: 4.7, reviews: 456, description: "11-inch Liquid Retina display, Apple M4 chip, Apple Pencil Pro support, landscape camera. Perfect for everyday.", features: ["11-inch Liquid Retina LED display", "Apple M4 chip (9-core CPU, 10-core GPU)", "8GB unified memory", "128GB storage", "USB-C with USB 3.0", "Landscape 12MP camera", "Touch ID in top button"], images: ["https://images.unsplash.com/photo-1587033411391-5d2f2f2023ce?w=400"] },
      { name: 'iPad 11th Gen (A16)', category: "tablets", price: 349, stock: 35, rating: 4.5, reviews: 2341, description: "10.9-inch Liquid Retina display, A16 Bionic chip, landscape camera, USB-C. The most affordable iPad.", features: ["10.9-inch Liquid Retina display", "A16 Bionic chip", "128GB storage", "Landscape 12MP camera", "USB-C", "Touch ID", "Apple Pencil (USB-C) support"], images: ["https://images.unsplash.com/photo-1557825835-70d97c19aaad?w=400"] },
      { name: 'Samsung Galaxy Tab S10 Ultra', category: "tablets", price: 1199, originalPrice: 1399, stock: 9, rating: 4.7, reviews: 234, description: "14.6-inch Dynamic AMOLED 2X 120Hz, MediaTek Dimensity 9300+, 12GB RAM, 256GB SSD. S Pen included.", features: ["14.6-inch Dynamic AMOLED 2X 120Hz", "MediaTek Dimensity 9300+", "12GB RAM + 256GB storage", "S Pen with Bluetooth", "Book Cover Keyboard included", "11,200mAh battery", "IP68 rating"], images: ["https://images.unsplash.com/photo-1561154464-82e9adf32764?w=400"] },
      { name: 'Samsung Galaxy Tab A11', category: "tablets", price: 199, stock: 40, rating: 4.3, reviews: 3456, description: "11-inch TFT display, great for entertainment and kids. Expandable storage up to 1TB.", features: ["11-inch TFT LCD display", "Octa-core processor", "64GB storage (expandable to 1TB)", "Quad speakers", "7040mAh battery", "USB-C", "Kids mode included"], images: ["https://images.unsplash.com/photo-1561154464-82e9adf32764?w=400"] },
      { name: 'Amazon Fire HD 10 (2023)', category: "tablets", price: 139, originalPrice: 179, stock: 55, rating: 4.3, reviews: 5678, description: "10.1-inch 1080p display, octa-core processor, 32GB storage, hands-free Alexa. Best budget tablet.", features: ["10.1-inch 1080p Full HD display", "Octa-core 2.0 GHz processor", "32GB storage (expandable to 1TB)", "Hands-free Alexa", "13-hour battery life", "USB-C 2.0", "Amazon Kids content included"], images: ["https://images.unsplash.com/photo-1561154464-82e9adf32764?w=400"] },

      /* ── WATCHES ── */
      { name: 'Apple Watch Series 11 (42mm GPS)', category: "watches", price: 399, stock: 25, badge: "New", rating: 4.8, reviews: 3456, description: "Always-On Retina LTPO OLED, S11 SiP, blood oxygen, ECG, temperature sensor, crash detection. The latest Apple Watch.", features: ["Always-On Retina LTPO OLED display", "S11 SiP (64-bit dual-core)", "Blood Oxygen + ECG app", "Temperature sensing", "Crash Detection + Fall Detection", "Water resistant 50m", "18-hour battery life"], images: ["https://images.unsplash.com/photo-1546868871-af0de0ae72e7?w=400"] },
      { name: 'Apple Watch Series 11 (46mm GPS)', category: "watches", price: 429, stock: 22, rating: 4.8, reviews: 2123, description: "Larger 46mm display, S11 SiP, all health sensors, faster charging, and the most advanced wearable display.", features: ["Always-On Retina LTPO OLED, 46mm", "S11 SiP (64-bit dual-core)", "Blood Oxygen + ECG app", "Temperature sensing", "Faster charging (0-80% in 45 min)", "Water resistant 50m", "36-hour battery in low power mode"], images: ["https://images.unsplash.com/photo-1546868871-af0de0ae72e7?w=400"] },
      { name: 'Apple Watch SE 3 (40mm GPS)', category: "watches", price: 249, stock: 30, rating: 4.6, reviews: 5678, description: "S9 SiP, crash detection, all-day fitness tracking. The best value Apple Watch.", features: ["Retina LTPO OLED display", "S9 SiP (64-bit dual-core)", "Crash Detection + Fall Detection", "Fitness tracking + Workout app", "Water resistant 50m", "18-hour battery life", "Family Setup support"], images: ["https://images.unsplash.com/photo-1546868871-af0de0ae72e7?w=400"] },
      { name: 'Apple Watch Ultra 3 (49mm)', category: "watches", price: 799, stock: 8, badge: "Premium", rating: 4.9, reviews: 1234, description: "49mm titanium, Precision dual-frequency GPS, siren, 36-hour battery, dive computer to 40m. The ultimate sports watch.", features: ["49mm titanium case, flat sapphire crystal", "Precision dual-frequency GPS", "86dB emergency siren", "Dive computer to 40m", "36-hour battery (72h low power)", "Action button + customizable", "Precision finding for iPhone"], images: ["https://images.unsplash.com/photo-1546868871-af0de0ae72e7?w=400"] },
      { name: 'Samsung Galaxy Watch8 (44mm BT)', category: "watches", price: 379, stock: 18, rating: 4.6, reviews: 2341, description: "Super AMOLED 44mm, Exynos W1000, BioActive sensor, Wear OS 5, Samsung Galaxy AI features.", features: ["1.5-inch Super AMOLED 44mm", "Exynos W1000 (3nm)", "BioActive sensor (heart rate, BIA, temperature)", "Wear OS 5 with One UI Watch 6", "Galaxy AI features", "IP68 + 5ATM + MIL-STD-810H", "60-hour battery (normal use)"], images: ["https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400"] },
      { name: 'Samsung Galaxy Watch8 Classic (47mm)', category: "watches", price: 449, stock: 12, rating: 4.7, reviews: 1567, description: "Classic design with rotating bezel, 47mm Super AMOLED, titanium grade, premium health suite.", features: ["1.6-inch Super AMOLED 47mm", "Rotating bezel navigation", "Titanium grade case", "Exynos W1000 (3nm)", "BioActive sensor + temperature", "Wear OS 5 + Galaxy AI", "80-hour battery (normal use)"], images: ["https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400"] },
      { name: 'Samsung Galaxy Watch Ultra', category: "watches", price: 649, stock: 6, badge: "Adventure", rating: 4.8, reviews: 876, description: "47mm titanium, 3000-nit display, dual-frequency GPS, emergency siren, 100m water resistant. Built for extremes.", features: ["47mm titanium cushion case", "3000-nit Super AMOLED", "Dual-frequency GPS (L1+L5)", "Emergency siren 86dB", "10ATM + IP68 + MIL-STD-810H", "Galaxy AI + Wear OS 5", "100-hour battery (power save mode)"], images: ["https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=400"] },
      { name: 'Google Pixel Watch 4 (41mm)', category: "watches", price: 349, stock: 20, rating: 4.5, reviews: 1890, description: "41mm Actua display, Tensor W3, Fitbit integration, loss of pulse detection. The best of Google + Fitbit.", features: ["1.3-inch Actua AMOLED 41mm", "Tensor W3 chip", "Fitbit health tracking + ECG", "Loss of pulse detection", "Crash Detection", "24-hour battery", "Wear OS 5 + Google AI"], images: ["https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=400"] },

      /* ── HEADPHONES ── */
      { name: 'Sony WH-1000XM6', category: "headphones", price: 449, stock: 35, badge: "Featured", rating: 4.9, reviews: 567, description: "Industry-leading noise cancellation with Auto NC Optimizer. 40-hour battery, Hi-Res Audio, multipoint connection.", features: ["Industry-leading ANC with Auto NC Optimizer", "40-hour battery life", "Hi-Res Audio Wireless (LDAC)", "Multipoint connection (2 devices)", "Speak-to-Chat technology", "Adaptive Sound Control", "Foldable premium design"], images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400"] },
      { name: 'AirPods Max Pro', category: "headphones", price: 649, stock: 11, rating: 4.7, reviews: 234, description: "Apple H2 chip, adaptive audio, USB-C with lossless audio. 40-hour battery. Ultra-premium over-ear headphones.", features: ["Apple H2 chip with adaptive audio", "USB-C with lossless audio", "40-hour battery", "Active Noise Cancellation", "Transparency mode", "Spatial Audio with dynamic head tracking", "Ultra-premium build with breathable knit"], images: ["https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400"] },
      { name: 'AirPods Pro 3 (USB-C)', category: "headphones", price: 249, stock: 45, badge: "Best Seller", rating: 4.8, reviews: 1234, description: "Apple H3 chip, adaptive audio, conversation awareness, USB-C MagSafe case with Find My speaker.", features: ["Apple H3 chip", "Adaptive Audio (ANC + Transparency)", "Conversation Awareness", "USB-C MagSafe charging case with Find My", "Personalized Spatial Audio", "Up to 6 hours listening (30h with case)", "IP54 dust and sweat resistant"], images: ["https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=400"] },
      { name: 'Samsung Galaxy Buds3 Pro', category: "headphones", price: 229, originalPrice: 249, stock: 30, rating: 4.6, reviews: 876, description: "Blade-light design, dual amps, 2-way speakers, Galaxy AI audio, adaptive ANC, IP57 rating.", features: ["Blade-light ergonomic design", "Dual amp + 2-way speaker system", "Adaptive ANC with siren detection", "Galaxy AI audio features", "IP57 water and dust resistant", "Up to 6 hours (26h with case)", "Bluetooth 5.4 + LE Audio"], images: ["https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400"] },
      { name: 'Bose QuietComfort Ultra', category: "headphones", price: 429, stock: 18, rating: 4.7, reviews: 654, description: "CustomTune ANC, Immersive Audio, 30-hour battery, world-class comfort. Bose signature sound.", features: ["CustomTune ANC (auto-calibrating)", "Bose Immersive Audio", "30-hour battery life", "SimpleSync for Bluetooth 5.3", "Snapdragon Sound certified", "Ultra-plush ear cushions", "USB-C + 3.5mm audio"], images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400"] },

      /* ── ACCESSORIES ── */
      { name: 'Logitech MX Master 3S', category: "accessories", price: 99, stock: 50, rating: 4.8, reviews: 890, description: "8K DPI optical sensor, quiet clicks, USB-C, 70-day battery. The ultimate productivity mouse.", features: ["8K DPI darkfield sensor", "Quiet click buttons", "USB-C rechargeable", "70-day battery life", "MagSpeed electromagnetic scroll wheel", "Connect up to 3 devices", "Ergonomic sculpted design"], images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400"] },
      { name: 'Keychron Q6 Pro', category: "accessories", price: 199, stock: 20, badge: "Best Seller", rating: 4.6, reviews: 156, description: "Full-size QMK/VIA wireless mechanical keyboard. Gateron Jupiter switches, RGB, aluminum frame.", features: ["Full-size 100% layout", "QMK/VIA programmable", "Gateron Jupiter switches", "Per-key RGB backlight", "6063 aluminum frame", "Bluetooth 5.1 + USB-C", "Hot-swappable switches"], images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400"] },
      { name: 'Samsung Odyssey G9 49" OLED', category: "accessories", price: 1399, originalPrice: 1799, stock: 6, badge: "Sale", rating: 4.7, reviews: 234, description: "49-inch Dual QHD 240Hz, 0.03ms, OLED, HDR1000, 32:9 super ultrawide. Immersive gaming monitor.", features: ["49-inch Dual QHD (5120x1440)", "240Hz refresh rate, 0.03ms response", "OLED panel with HDR1000", "32:9 super ultrawide", "AMD FreeSync Premium Pro", "Built-in KVM switch", "1000R curvature"], images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400"] },
      { name: 'SteelSeries Arctis Nova Pro', category: "accessories", price: 349, stock: 16, rating: 4.5, reviews: 312, description: "Premium gaming headset with Hi-Res Audio, active noise cancellation, hot-swappable battery system.", features: ["Hi-Res Audio certified", "Active Noise Cancellation", "Dual hot-swappable batteries", "ClearCast gen 2 microphone", "Sonar audio software suite", "Comfort-focused design", "Multi-platform connectivity"], images: ["https://images.unsplash.com/photo-1599669454699-248893623440?w=400"] },
      { name: 'Apple Magic Keyboard with Touch ID', category: "accessories", price: 149, stock: 40, rating: 4.6, reviews: 567, description: "Full-size keyboard with Touch ID, numeric keypad, wireless charging. Seamless Mac integration.", features: ["Touch ID for secure unlock", "Numeric keypad included", "Wireless rechargeable battery", "USB-C to Lightning cable", "Low-profile scissor mechanism", "1-month battery life", "Seamless Mac + iCloud pairing"], images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400"] },
      { name: 'Anker 100W GaN Charger', category: "accessories", price: 49, stock: 100, rating: 4.7, reviews: 1234, description: "Compact 100W GaN III USB-C charger. 3 ports, universal compatibility. Charge MacBook Pro, iPad, iPhone simultaneously.", features: ["100W total output (GaN III tech)", "2x USB-C + 1x USB-A", "Charge MacBook Pro full speed", "GaN III compact design", "Universal compatibility", "Smart power distribution", "MultiProtect safety system"], images: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400"] },

      /* ── GAME TOP-UPS ── */
      { name: 'Valorant Points — 10,000 VP', category: "game-topup", price: 99.99, stock: 999, rating: 4.5, reviews: 3456, description: "Instant digital delivery of 10,000 Valorant Points. Unlock skins, battle passes, and agents.", features: ["10,000 Valorant Points", "Works on all Valorant regions", "Instant email delivery", "Redeem at playvalorant.com", "Secure transaction, 24/7 support"], images: [], specs: { type: "Valorant Points", amount: "10,000 VP", delivery: "Instant", platform: "Valorant" } },
      { name: 'Fortnite V-Bucks — 13,500 V-Bucks', category: "game-topup", price: 79.99, stock: 999, badge: "Popular", rating: 4.4, reviews: 5678, description: "13,500 V-Bucks for Fortnite. Unlock battle passes, emotes, outfits, and the latest season content.", features: ["13,500 V-Bucks", "Cross-platform redemption", "Instant delivery via email", "Works on PC, Console, Mobile"], images: [], specs: { type: "V-Bucks", amount: "13,500", delivery: "Instant", platform: "Fortnite" } },
      { name: 'FC 25 Ultimate Team — 12,000 FC Points', category: "game-topup", price: 99.99, stock: 999, rating: 4.6, reviews: 7654, description: "12,000 FC Points for EA FC 25 Ultimate Team. Build your dream squad and open packs instantly.", features: ["12,000 FC Points", "Works on All Platforms", "Instant Email Delivery", "Official EA Partner"], images: [], specs: { type: "Ultimate Team Points", amount: "12,000 Points", delivery: "Instant", platform: "EA FC 25" } },
      { name: 'PUBG Mobile — 3,000 UC', category: "game-topup", price: 29.99, stock: 999, rating: 4.5, reviews: 8765, description: "3,000 Unknown Cash for PUBG Mobile. Get skins, emotes, and Royale Pass.", features: ["3,000 UC", "Works on Android & iOS", "Instant Delivery", "Cheapest Rates Guaranteed"], images: [], specs: { type: "Unknown Cash", amount: "3,000 UC", delivery: "Instant", platform: "PUBG Mobile" } },
      { name: 'Genshin Impact — 6,480 Genesis Crystals', category: "game-topup", price: 99.99, stock: 999, rating: 4.7, reviews: 5678, description: "6,480 Genesis Crystals + Bonus Crystals. Top up your adventures in Teyvat.", features: ["6,480 + Bonus Crystals", "Works on All Servers", "Instant Delivery", "Welkin Moon Compatible"], images: [], specs: { type: "Genesis Crystals", amount: "6,480 + Bonus", delivery: "Instant", platform: "Genshin Impact" } },
      { name: 'Call of Duty — 5,000 CP', category: "game-topup", price: 39.99, stock: 999, rating: 4.4, reviews: 3456, description: "5,000 Call of Duty Points for Warzone and Black Ops. Grab battle passes, bundles, and blueprints.", features: ["5,000 COD Points", "Cross-platform (PC, PS, Xbox, Battle.net)", "Instant email delivery", "Season content compatible"], images: [], specs: { type: "COD Points", amount: "5,000 CP", delivery: "Instant", platform: "Call of Duty" } },
      { name: 'Roblox — 10,000 Robux', category: "game-topup", price: 99.99, stock: 999, badge: "Best Seller", rating: 4.6, reviews: 12345, description: "10,000 Robux for Roblox. Premium items, avatar accessories, and game passes.", features: ["10,000 Robux", "Works on all Roblox platforms", "Instant email delivery", "No tax or fees"], images: [], specs: { type: "Robux", amount: "10,000 Robux", delivery: "Instant", platform: "Roblox" } },
      { name: 'Mobile Legends — 5,000 Diamonds', category: "game-topup", price: 49.99, stock: 999, rating: 4.3, reviews: 2341, description: "5,000 Diamonds for Mobile Legends. Unlock heroes, skins, and battle passes.", features: ["5,000 Diamonds", "Works on Android & iOS", "Instant delivery via code", "Weekly pass compatible"], images: [], specs: { type: "Diamonds", amount: "5,000 Diamonds", delivery: "Instant", platform: "Mobile Legends" } },

      /* ── GIFT CARDS ── */
      { name: 'PlayStation Network $100 Gift Card', category: "gift-cards", price: 100, stock: 500, badge: "Popular", rating: 4.8, reviews: 5678, description: "Digital PSN gift card delivered instantly via email. Redeem on PlayStation Store for games, DLC, and more.", features: ["$100 PSN credit", "Instant email delivery", "Redeem on PS Store", "No expiration date"], images: ["https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=400"], specs: { type: "PSN Gift Card", value: "$100", delivery: "Instant", platform: "PlayStation" } },
      { name: 'Steam $50 Wallet Code', category: "gift-cards", price: 50, stock: 500, rating: 4.7, reviews: 4567, description: "Add $50 to your Steam Wallet instantly. Buy games, DLC, and community items on Steam.", features: ["$50 Steam Wallet credit", "Instant delivery", "Works worldwide", "Redeem on Steam client or web"], images: ["https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=400"], specs: { type: "Steam Wallet", value: "$50", delivery: "Instant", platform: "Steam" } },
      { name: 'Nintendo eShop $25 Gift Card', category: "gift-cards", price: 25, stock: 500, rating: 4.6, reviews: 3456, description: "Digital Nintendo eShop gift card for Switch, Wii U, and 3DS. Get the best Nintendo games.", features: ["$25 Nintendo eShop credit", "Works on Switch, Wii U, 3DS", "Instant email delivery", "Region-free redemption"], images: ["https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=400"], specs: { type: "Nintendo eShop", value: "$25", delivery: "Instant", platform: "Nintendo Switch" } },
      { name: 'Xbox $50 Gift Card', category: "gift-cards", price: 50, stock: 500, rating: 4.7, reviews: 3123, description: "Digital Xbox gift card for games, add-ons, and subscriptions. Works on Xbox Series X|S, Xbox One, and PC.", features: ["$50 Xbox credit", "Xbox Series X|S, Xbox One, Windows", "Instant email delivery", "Game Pass compatible"], images: ["https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=400"], specs: { type: "Xbox Gift Card", value: "$50", delivery: "Instant", platform: "Xbox" } },
      { name: 'Google Play $25 Gift Card', category: "gift-cards", price: 25, stock: 500, rating: 4.5, reviews: 6789, description: "Digital Google Play gift card for apps, games, movies, and books on the Google Play Store.", features: ["$25 Google Play credit", "Works on Android & Google services", "Instant email delivery", "No expiration"], images: ["https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=400"], specs: { type: "Google Play", value: "$25", delivery: "Instant", platform: "Google Play" } },
      { name: 'Apple Gift Card $100', category: "gift-cards", price: 100, stock: 500, badge: "Popular", rating: 4.8, reviews: 4321, description: "Digital Apple Gift Card for Apple Store, App Store, iTunes, Apple Music, and iCloud+. One card for everything Apple.", features: ["$100 Apple credit", "Works on App Store, iTunes, Apple Music, iCloud", "Instant email delivery", "Hardware and services eligible"], images: ["https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=400"], specs: { type: "Apple Gift Card", value: "$100", delivery: "Instant", platform: "Apple Ecosystem" } },
    ];

    for (const p of products) {
      const id = p.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') + '-' + uuidv4().slice(0, 6);
      const exists = await query("SELECT id FROM products WHERE name = $1", [p.name]);
      if (exists.rows.length > 0) continue;
      await query(
        `INSERT INTO products (id, name, category, price, "originalPrice", rating, reviews, description, features, images, stock, badge, specs, "createdAt")
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10::jsonb,$11,$12,$13::jsonb,$14)`,
        [id, p.name, p.category, p.price, p.originalPrice || null, p.rating || 4.5, p.reviews || 0,
         p.description, JSON.stringify(p.features || []), JSON.stringify(p.images || []),
         p.stock, p.badge || null, JSON.stringify(p.specs || {}), new Date(Date.now() - Math.random() * 90 * 86400000).toISOString()]
      );
    }

  } catch (e) {
    console.error("Seed error:", e.message);
  }
}
